# linuxptp profile for interface eno2np1 using Layer-2 transport.
# Use this profile if UDPv4 profile does not see Sync/Announce traffic.

[global]
twoStepFlag              1
slaveOnly                1
time_stamping            hardware
network_transport        L2
delay_mechanism          E2E
domainNumber             0
announceReceiptTimeout   3
syncReceiptTimeout       3
logAnnounceInterval      1
logSyncInterval          0
logMinDelayReqInterval   0
summary_interval         1

[eno2np1]
